name: build-on-firefox
on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types: [opened, reopened, edited, synchronize]
    paths:
      - '**.js'
      - 'import-font.css'
      - 'pwd-font.ttf'
jobs:
  buildFF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Firefox
      run: |
        npm i
        npm run test.FF