name: build-on-firefox
on:
  push:
    paths:
      - '**.js'
      - 'import-font.css'
      - 'pwd-font.ttf'
jobs:
  buildFF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Firefox
      run: |
        npm i
        npm run test.FF
